#!/usr/bin/env tsx
// Run with: npm run import-class-abilities
// Reads class data from docs/nimblenomicon/src/data/classes.json
// and writes src/lib/class-abilities.ts with fully-typed static ability data.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const JSON_PATH = join(PROJECT_ROOT, 'docs/nimblenomicon/src/data/classes.json');
const OUT_PATH = join(PROJECT_ROOT, 'src/lib/class-abilities.ts');

// ── JSON shape (what we read) ──────────────────────────────────────────────────

interface RawAbility {
	name: string;
	description: string;
}
interface RawLevel {
	level: number;
	abilities: RawAbility[];
}
interface RawAbilityList {
	name: string;
	description: string;
	items: RawAbility[];
}
interface RawSubclass {
	name: string;
	levels: RawLevel[];
}
interface RawClass {
	name: string;
	levels: RawLevel[];
	abilityLists?: RawAbilityList[];
	subclasses?: RawSubclass[];
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function stripHtml(s: string): string {
	return s.replace(/<[^>]+>/g, '');
}

function esc(s: string): string {
	return s
		.replaceAll('\\', String.raw`\\`)
		.replaceAll("'", String.raw`\'`)
		.replaceAll('\n', '\\n')
		.replaceAll('\r', '');
}

function serializeAbility(a: RawAbility, indent: string): string {
	return `${indent}{ name: '${esc(a.name)}', desc: '${esc(stripHtml(a.description))}' }`;
}

function serializeLevel(l: RawLevel, indent: string): string {
	const inner = indent + '\t';
	const abilities = l.abilities.map((a) => serializeAbility(a, inner)).join(',\n');
	return `${indent}{\n${inner}level: ${l.level},\n${inner}abilities: [\n${abilities},\n${inner}],\n${indent}}`;
}

function serializeAbilityList(al: RawAbilityList, indent: string): string {
	const inner = indent + '\t';
	const items = al.items.map((a) => serializeAbility(a, inner + '\t')).join(',\n');
	return (
		`${indent}{\n` +
		`${inner}name: '${esc(al.name)}',\n` +
		`${inner}desc: '${esc(stripHtml(al.description))}',\n` +
		`${inner}items: [\n${items},\n${inner}],\n` +
		`${indent}}`
	);
}

function serializeSubclass(sc: RawSubclass, indent: string): string {
	const inner = indent + '\t';
	const levels = sc.levels.map((l) => serializeLevel(l, inner + '\t')).join(',\n');
	return (
		`${indent}{\n` +
		`${inner}name: '${esc(sc.name)}',\n` +
		`${inner}levels: [\n${levels},\n${inner}],\n` +
		`${indent}}`
	);
}

function serializeClass(cls: RawClass): string {
	const abilityLists = (cls.abilityLists ?? [])
		.map((al) => serializeAbilityList(al, '\t\t\t'))
		.join(',\n');
	const subclasses = (cls.subclasses ?? [])
		.map((sc) => serializeSubclass(sc, '\t\t\t'))
		.join(',\n');
	const levels = cls.levels.map((l) => serializeLevel(l, '\t\t\t')).join(',\n');

	return (
		`\t'${esc(cls.name)}': {\n` +
		`\t\tname: '${esc(cls.name)}',\n` +
		`\t\tlevels: [\n${levels},\n\t\t],\n` +
		`\t\tabilityLists: [\n${abilityLists ? abilityLists + ',\n' : ''}\t\t],\n` +
		`\t\tsubclasses: [\n${subclasses ? subclasses + ',\n' : ''}\t\t],\n` +
		`\t}`
	);
}

// ── Main ───────────────────────────────────────────────────────────────────────

const raw: RawClass[] = JSON.parse(readFileSync(JSON_PATH, 'utf8'));

const entries = raw.map(serializeClass).join(',\n');

const output =
	`// AUTO-GENERATED by scripts/import-class-abilities.ts — do not edit by hand.\n` +
	`// Re-run \`npm run import-class-abilities\` to regenerate from docs/nimblenomicon/src/data/classes.json.\n\n` +
	`export interface ClassAbility {\n` +
	`\tname: string;\n` +
	`\tdesc: string;\n` +
	`}\n\n` +
	`export interface ClassAbilityList {\n` +
	`\tname: string;\n` +
	`\tdesc: string;\n` +
	`\titems: ClassAbility[];\n` +
	`}\n\n` +
	`export interface ClassSubclassLevel {\n` +
	`\tlevel: number;\n` +
	`\tabilities: ClassAbility[];\n` +
	`}\n\n` +
	`export interface ClassSubclass {\n` +
	`\tname: string;\n` +
	`\tlevels: ClassSubclassLevel[];\n` +
	`}\n\n` +
	`export interface ClassLevel {\n` +
	`\tlevel: number;\n` +
	`\tabilities: ClassAbility[];\n` +
	`}\n\n` +
	`export interface ClassData {\n` +
	`\tname: string;\n` +
	`\tlevels: ClassLevel[];\n` +
	`\tabilityLists: ClassAbilityList[];\n` +
	`\tsubclasses: ClassSubclass[];\n` +
	`}\n\n` +
	`export const classAbilities: Record<string, ClassData> = {\n${entries},\n};\n`;

writeFileSync(OUT_PATH, output, 'utf8');
console.log(`Wrote src/lib/class-abilities.ts (${raw.length} classes).`);
